-- CREATE DEPARTMENT TABLE
CREATE TABLE TBL_DEPARTMENT AS
(Select department
from 
    (Select department, count(*) as NUMBER_PER_DEPARTMENT
    FROM TBL_EMPLOYEE
    GROUP BY DEPARTMENT));

-- CHeck the data
SELECT department
FROM tbl_department;
    
-- ADDING A department head column
ALter table TBL_DEPARTMENT
ADD DEPARTMENT_HEAD VARCHAR2(20 CHAR);

--Check
SELECT *
FROM tbl_department;
------------------------------------------------------------------
-- JOIN THREE TABLES

SELECT TBL_DEPARTMENT.department, sum(AMOUNT) AS SUM_OF_AMOUNT
FROM TBL_DEPARTMENT
LEFT JOIN TBL_EMPLOYEE
ON TBL_DEPARTMENT.DEPARTMENT = TBL_EMPLOYEE. DEPARTMENT
LEFT JOIN TBL_TRANSACTION
ON TBL_EMPLOYEE.EMPLOYEE_NUMBER = TBL_TRANSACTION.EMPLOYEE_NUMBER
GROUP BY TBL_DEPARTMENT.department;

--- CHANGING the DATA in DEPARTMENT TABLE

TRUNCATE TABLE TBL_DEPARTMENT;
COMMIT;
INSERT INTO TBL_DEPARTMENT VALUES('Customer Relations','Andrew');
INSERT INTO TBL_DEPARTMENT VALUES('Commercial','Bryan');
INSERT INTO TBL_DEPARTMENT VALUES('HR','Catherine');
INSERT INTO TBL_DEPARTMENT VALUES('Litigation','Andrew');
INSERT INTO TBL_DEPARTMENT VALUES('Accounts','James');
COMMIT;

--CHECK
SELECT department,department_head
FROM tbl_department;

SELECT department,DEPARTMENT_HEAD ,sum(AMOUNT) AS SUM_OF_AMOUNT
FROM TBL_DEPARTMENT
LEFT JOIN TBL_EMPLOYEE
USING (DEPARTMENT)
LEFT JOIN TBL_TRANSACTION
USING (EMPLOYEE_NUMBER)
GROUP BY department, DEPARTMENT_HEAD;

